export type PlatformItem = {
  slug: string;
  title: string;
  shortTitle?: string;
  description?: string;
  emoji: string;
  brandGradient?: string;
  brandGlow?: string;
  isFeatured: boolean;
  isActive: boolean;
  sortOrder: number;
};

export const PLATFORM_DEFINITIONS: PlatformItem[] = [
  {
    slug: "instagram",
    title: "Instagram",
    emoji: "📸",
    brandGradient: "from-pink-500/25 via-fuchsia-500/20 to-orange-400/20",
    brandGlow: "bg-pink-500/20",
    description: "Takipçi, beğeni, izlenme, yorum ve daha fazlası",
    isFeatured: true,
    isActive: true,
    sortOrder: 1,
  },
  {
    slug: "tiktok",
    title: "TikTok",
    emoji: "🎵",
    brandGradient: "from-cyan-400/20 via-white/5 to-rose-500/20",
    brandGlow: "bg-cyan-400/20",
    description: "Takipçi, beğeni, izlenme ve etkileşim hizmetleri",
    isFeatured: true,
    isActive: true,
    sortOrder: 2,
  },
  {
    slug: "youtube",
    title: "YouTube",
    emoji: "▶️",
    brandGradient: "from-red-500/25 via-rose-500/10 to-white/5",
    brandGlow: "bg-red-500/20",
    description: "Abone, izlenme, beğeni ve yorum hizmetleri",
    isFeatured: true,
    isActive: true,
    sortOrder: 3,
  },
  {
    slug: "telegram",
    title: "Telegram",
    emoji: "✈️",
    brandGradient: "from-sky-400/25 via-blue-500/10 to-white/5",
    brandGlow: "bg-sky-400/20",
    description: "Üye, görüntüleme, reaksiyon ve kanal destek hizmetleri",
    isFeatured: true,
    isActive: true,
    sortOrder: 4,
  },
  {
    slug: "spotify",
    title: "Spotify",
    emoji: "🎧",
    brandGradient: "from-emerald-400/25 via-green-500/10 to-white/5",
    brandGlow: "bg-emerald-400/20",
    description: "Dinlenme, takipçi ve müzik büyütme hizmetleri",
    isFeatured: true,
    isActive: true,
    sortOrder: 5,
  },
  {
    slug: "facebook",
    title: "Facebook",
    emoji: "📘",
    brandGradient: "from-blue-500/25 via-sky-500/10 to-white/5",
    brandGlow: "bg-blue-500/20",
    description: "Beğeni, takipçi, görüntülenme ve etkileşim hizmetleri",
    isFeatured: true,
    isActive: true,
    sortOrder: 6,
  },
  {
    slug: "x",
    title: "X / Twitter",
    shortTitle: "X",
    emoji: "𝕏",
    brandGradient: "from-zinc-300/15 via-white/5 to-zinc-900/30",
    brandGlow: "bg-white/10",
    description: "Takipçi, beğeni, görüntülenme ve retweet hizmetleri",
    isFeatured: true,
    isActive: true,
    sortOrder: 7,
  },
  {
    slug: "twitch",
    title: "Twitch",
    emoji: "🟣",
    brandGradient: "from-violet-500/20 via-purple-500/10 to-white/5",
    brandGlow: "bg-violet-500/20",
    description: "Takipçi, görüntülenme ve yayın etkileşim hizmetleri",
    isFeatured: false,
    isActive: true,
    sortOrder: 8,
  },
  {
    slug: "kick",
    title: "Kick",
    emoji: "🟢",
    brandGradient: "from-lime-400/20 via-green-500/10 to-white/5",
    brandGlow: "bg-lime-400/20",
    description: "Takipçi, görüntülenme ve yayın destek hizmetleri",
    isFeatured: false,
    isActive: true,
    sortOrder: 9,
  },
  {
    slug: "discord",
    title: "Discord",
    emoji: "💬",
    brandGradient: "from-indigo-500/20 via-violet-500/10 to-white/5",
    brandGlow: "bg-indigo-500/20",
    description: "Üye ve topluluk büyütme hizmetleri",
    isFeatured: false,
    isActive: true,
    sortOrder: 10,
  },
  {
    slug: "snapchat",
    title: "Snapchat",
    emoji: "👻",
    brandGradient: "from-yellow-300/20 via-white/10 to-white/5",
    brandGlow: "bg-yellow-300/20",
    description: "Görüntülenme ve etkileşim hizmetleri",
    isFeatured: false,
    isActive: true,
    sortOrder: 11,
  },
  {
    slug: "pinterest",
    title: "Pinterest",
    emoji: "📌",
    brandGradient: "from-red-500/20 via-rose-500/10 to-white/5",
    brandGlow: "bg-red-500/20",
    description: "Takipçi ve görüntülenme hizmetleri",
    isFeatured: false,
    isActive: true,
    sortOrder: 12,
  },
  {
    slug: "linkedin",
    title: "LinkedIn",
    emoji: "💼",
    brandGradient: "from-blue-600/20 via-sky-500/10 to-white/5",
    brandGlow: "bg-blue-600/20",
    description: "Takipçi ve etkileşim hizmetleri",
    isFeatured: false,
    isActive: true,
    sortOrder: 13,
  },
  {
    slug: "reddit",
    title: "Reddit",
    emoji: "👽",
    brandGradient: "from-orange-500/20 via-red-500/10 to-white/5",
    brandGlow: "bg-orange-500/20",
    description: "Upvote, görüntülenme ve etkileşim hizmetleri",
    isFeatured: false,
    isActive: true,
    sortOrder: 14,
  },
  {
    slug: "threads",
    title: "Threads",
    emoji: "🧵",
    brandGradient: "from-zinc-300/15 via-white/5 to-zinc-900/30",
    brandGlow: "bg-white/10",
    description: "Takipçi, beğeni ve görüntülenme hizmetleri",
    isFeatured: false,
    isActive: true,
    sortOrder: 15,
  },
  {
    slug: "apple-music",
    title: "Apple Music",
    emoji: "🍎",
    brandGradient: "from-pink-500/20 via-rose-500/10 to-white/5",
    brandGlow: "bg-pink-500/20",
    description: "Dinlenme ve müzik büyütme hizmetleri",
    isFeatured: false,
    isActive: true,
    sortOrder: 16,
  },
  {
    slug: "soundcloud",
    title: "SoundCloud",
    emoji: "☁️",
    brandGradient: "from-orange-400/20 via-amber-500/10 to-white/5",
    brandGlow: "bg-orange-400/20",
    description: "Dinlenme, beğeni ve takipçi hizmetleri",
    isFeatured: false,
    isActive: true,
    sortOrder: 17,
  },
  {
    slug: "audiomack",
    title: "Audiomack",
    emoji: "🎶",
    brandGradient: "from-yellow-400/20 via-orange-500/10 to-white/5",
    brandGlow: "bg-yellow-400/20",
    description: "Dinlenme ve takipçi hizmetleri",
    isFeatured: false,
    isActive: true,
    sortOrder: 18,
  },
  {
    slug: "deezer",
    title: "Deezer",
    emoji: "🎼",
    brandGradient: "from-purple-500/20 via-pink-500/10 to-white/5",
    brandGlow: "bg-purple-500/20",
    description: "Dinlenme ve müzik büyütme hizmetleri",
    isFeatured: false,
    isActive: true,
    sortOrder: 19,
  },
  {
    slug: "shazam",
    title: "Shazam",
    emoji: "🎤",
    brandGradient: "from-sky-500/20 via-blue-500/10 to-white/5",
    brandGlow: "bg-sky-500/20",
    description: "Müzik keşif ve etkileşim hizmetleri",
    isFeatured: false,
    isActive: true,
    sortOrder: 20,
  },
  {
    slug: "boomplay",
    title: "Boomplay",
    emoji: "🔊",
    brandGradient: "from-emerald-500/20 via-lime-500/10 to-white/5",
    brandGlow: "bg-emerald-500/20",
    description: "Dinlenme ve müzik platformu büyütme hizmetleri",
    isFeatured: false,
    isActive: true,
    sortOrder: 21,
  },
  {
    slug: "steam",
    title: "Steam",
    emoji: "🎮",
    brandGradient: "from-slate-400/15 via-blue-900/20 to-white/5",
    brandGlow: "bg-slate-400/20",
    description: "Topluluk ve etkileşim hizmetleri",
    isFeatured: false,
    isActive: true,
    sortOrder: 22,
  },
  {
    slug: "xbox",
    title: "Xbox",
    emoji: "🕹️",
    brandGradient: "from-green-500/20 via-lime-500/10 to-white/5",
    brandGlow: "bg-green-500/20",
    description: "Topluluk ve profil destek hizmetleri",
    isFeatured: false,
    isActive: true,
    sortOrder: 23,
  },
  {
    slug: "vk",
    title: "VK",
    emoji: "🔵",
    brandGradient: "from-blue-500/20 via-sky-500/10 to-white/5",
    brandGlow: "bg-blue-500/20",
    description: "Takipçi, beğeni ve görüntülenme hizmetleri",
    isFeatured: false,
    isActive: true,
    sortOrder: 24,
  },
  {
    slug: "rutube",
    title: "Rutube",
    emoji: "📺",
    brandGradient: "from-red-500/20 via-rose-500/10 to-white/5",
    brandGlow: "bg-red-500/20",
    description: "İzlenme ve kanal büyütme hizmetleri",
    isFeatured: false,
    isActive: true,
    sortOrder: 25,
  },
  {
    slug: "ok-ru",
    title: "OK.ru",
    emoji: "🟠",
    brandGradient: "from-orange-500/20 via-amber-500/10 to-white/5",
    brandGlow: "bg-orange-500/20",
    description: "Takipçi ve etkileşim hizmetleri",
    isFeatured: false,
    isActive: true,
    sortOrder: 26,
  },
  {
    slug: "dzen",
    title: "Dzen",
    emoji: "📰",
    brandGradient: "from-zinc-300/15 via-white/5 to-zinc-900/30",
    brandGlow: "bg-white/10",
    description: "İzlenme ve kanal destek hizmetleri",
    isFeatured: false,
    isActive: true,
    sortOrder: 27,
  },
  {
    slug: "github",
    title: "GitHub",
    emoji: "🐙",
    brandGradient: "from-zinc-300/15 via-white/5 to-zinc-900/30",
    brandGlow: "bg-white/10",
    description: "Repo ve profil görünürlüğü destek hizmetleri",
    isFeatured: false,
    isActive: true,
    sortOrder: 28,
  },
  {
    slug: "tumblr",
    title: "Tumblr",
    emoji: "📝",
    brandGradient: "from-sky-500/20 via-blue-500/10 to-white/5",
    brandGlow: "bg-sky-500/20",
    description: "Takipçi ve etkileşim hizmetleri",
    isFeatured: false,
    isActive: true,
    sortOrder: 29,
  },
  {
    slug: "bluesky",
    title: "Bluesky",
    emoji: "🌤️",
    brandGradient: "from-sky-400/20 via-blue-500/10 to-white/5",
    brandGlow: "bg-sky-400/20",
    description: "Takipçi ve etkileşim hizmetleri",
    isFeatured: false,
    isActive: true,
    sortOrder: 30,
  },
  {
    slug: "vimeo",
    title: "Vimeo",
    emoji: "🎬",
    brandGradient: "from-sky-500/20 via-cyan-500/10 to-white/5",
    brandGlow: "bg-sky-500/20",
    description: "İzlenme ve video büyütme hizmetleri",
    isFeatured: false,
    isActive: true,
    sortOrder: 31,
  },
  {
    slug: "google-review",
    title: "Google Review",
    emoji: "⭐",
    brandGradient: "from-yellow-400/20 via-amber-500/10 to-white/5",
    brandGlow: "bg-yellow-400/20",
    description: "Yorum ve değerlendirme destek hizmetleri",
    isFeatured: false,
    isActive: true,
    sortOrder: 32,
  },
  {
    slug: "google-maps",
    title: "Google Maps",
    emoji: "📍",
    brandGradient: "from-emerald-400/20 via-blue-500/10 to-red-500/10",
    brandGlow: "bg-emerald-400/20",
    description: "Harita yorum ve görünürlük hizmetleri",
    isFeatured: false,
    isActive: true,
    sortOrder: 33,
  },
  {
    slug: "whatsapp",
    title: "WhatsApp",
    emoji: "🟢",
    brandGradient: "from-emerald-400/20 via-green-500/10 to-white/5",
    brandGlow: "bg-emerald-400/20",
    description: "Kanal ve topluluk destek hizmetleri",
    isFeatured: false,
    isActive: true,
    sortOrder: 34,
  },
];

export function getAllPlatforms() {
  return PLATFORM_DEFINITIONS
    .filter((item) => item.isActive)
    .sort((a, b) => a.sortOrder - b.sortOrder);
}

export function getFeaturedPlatforms() {
  return PLATFORM_DEFINITIONS
    .filter((item) => item.isActive && item.isFeatured)
    .sort((a, b) => a.sortOrder - b.sortOrder);
}

export function getSecondaryPlatforms() {
  return PLATFORM_DEFINITIONS
    .filter((item) => item.isActive && !item.isFeatured)
    .sort((a, b) => a.sortOrder - b.sortOrder);
}

export function getPlatformBySlug(slug: string) {
  return PLATFORM_DEFINITIONS.find((item) => item.slug === slug);
}